config/routes.rb
Rails.application.routes.draw do
  resources :cohort_instructors
  resources :cohort_students
  resources :grades
  resources :cohorts
  resources :courses
  resources :students
  resources :instructors
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :cohort_student
  has_many :cohorts, through: :cohort_student
  has_many :instructors
  has_many :instructors, through: :cohorts
  validates :first_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :last_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :high_deg, presence: true, length: { in: 2..3 }
  validates :age, presence: true, numericality: {integer_only: true, less_than: 100 }
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :require_login
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    @students_list = @students.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { redirect_to new_student_path, alert: "Student was not created: #{@student.errors.full_messages.to_sentence}" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { redirect_to edit_student_path, alert: "Student was not updated: #{@student.errors.full_messages.to_sentence}" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :age, :high_deg)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<h3>Student Info:</h3>

<%= form_with(model: student, local: true) do |form| %>
  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_Name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :high_deg %>
    <%= form.text_field :high_deg %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<br />
<h1>Editing Student</h1>
<br />
<hr>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<br />
<h1 style="display: inline-block;">Students</h1>
<%= link_to 'New Student', new_student_path %>
<br />

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cohorts</th>
      <th>Edit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<%= will_paginate @students_list %>
  <tbody>
    <% @students_list.each do |student| %>
      <tr>
        <td><%= "#{student.first_name} #{student.last_name}" %></td>
        <td><% student.cohorts.each do | cohort | %>| 
          <%= link_to "#{cohort.name}", edit_cohort_path(cohort.id) %> |
          <% end %>
        </td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @students_list %>

app/views/students/new.html.erb
<br />
<h1>New Student</h1>
<br />
<hr>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<br /><h1><%= @student.full_name %></h1><br /><hr><br />

<h3><%="#{@student.first_name} currently attends the following courses: "%></h3>
    <% @student.cohorts.each do |cohort| %>
        <%= link_to "#{cohort.name}", edit_cohort_path(cohort)%><br />
    <% end %>
  <br />
<h3><%="#{@student.first_name} is taught by: "%></h3>
    <% @student.instructors.uniq.each do |instructor| %>
        <%= link_to "#{instructor.full_name}", edit_instructor_path(instructor)%><br />
    <% end %>
    <br />
<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', student_path %>