config/routes.rb
Rails.application.routes.draw do
  resources :cohort_instructors
  resources :cohort_students
  resources :grades
  resources :cohorts
  resources :courses
  resources :students
  resources :instructors
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :cohort_instructors
  has_many :cohorts, through: :cohort_instructors
  has_many :students
  has_many :students, through: :cohorts
  validates :first_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :last_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letter" }
  validates :salary, presence: true, numericality: { integer_only: true, greater_than: 100000 }
  validates :high_deg, presence: true, length: { in: 2..3 }
  validates :age, presence: true, numericality: {integer_only: true, less_than: 100 }
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :require_login
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
    @instructors_list = @instructors.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { redirect_to new_instructor_path, alert: "Instructor was not created: #{@instructor.errors.full_messages.to_sentence}" }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { redirect_to edit_instructor_path, alert: "Instructor was not updated: #{@instructor.errors.full_messages.to_sentence}" }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:first_name, :last_name, :salary, :high_deg, :age)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<h3>Instructor Info:</h3>

<%= form_with(model: instructor, local: true) do |form| %>
  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.number_field :salary %>
  </div>

  <div class="field">
    <%= form.label :high_deg %>
    <%= form.text_field :high_deg %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<br />
<h1>Editing Instructor</h1>
<br />
<hr>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<br />
<h1 style="display: inline-block;">Instructors</h1>
<%= link_to 'New Instructor', new_instructor_path %>
<br />

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Salary</th>
      <th>Highest Degree</th>
      <th>Cohorts</th>
      <th colspan="3">Edit</th>
    </tr>
  </thead>

  <%= will_paginate @instructors_list %>
  <tbody>
    <% @instructors_list.each do |instructor| %>
      <tr>
        <td><%= "#{instructor.first_name} #{instructor.last_name}" %></td>
        <td>&#165;<%= instructor.salary %></td>
        <td><%= instructor.high_deg %></td>
        <td>|
          <% instructor.cohorts.each do | cohort |%>
          <%= cohort.name %> <%= link_to 'Show', cohort %> |
          <% end %>
        </td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @instructors_list %>

app/views/instructors/new.html.erb
<br />
<h1>New Instructor</h1>
<br />
<hr>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<br /><h1><%= @instructor.full_name %></h1>
<br />
<hr>
<br />

<h3><%="#{@instructor.first_name} currently teaches the following courses: "%></h3>
    <% @instructor.cohorts.each do |cohort| %>
        <%= link_to "#{cohort.name}", edit_cohort_path(cohort)%><br />
    <% end %>
  <br />
<h3><%="#{@instructor.first_name} currently teaches the following students: "%></h3>
    <% @instructor.students.each do |student| %>
        <%= link_to "#{student.full_name}", edit_student_path(student)%><br />
    <% end %>
    <br />
<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>