config/routes.rb
Rails.application.routes.draw do
  resources :cohort_instructors
  resources :cohort_students
  resources :grades
  resources :cohorts
  resources :courses
  resources :students
  resources :instructors
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :require_login
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
    @courses_list = @courses.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { redirect_to new_course_path, alert: "Course was not created: #{@course.errors.full_messages.to_sentence}." }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { redirect_to edit_course_path,  alert: "Course was not updated: #{@course.errors.full_messages.to_sentence}." }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :hours)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<h3>Course Info:</h3>
<%= form_with(model: course, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hours %>
    <%= form.text_field :hours %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<br />
<h1>Editing Course</h1>
<br />
<hr>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<br />
<h1 style="display: inline-block;">Courses</h1>
<%= link_to 'New Course', new_course_path %>

  <br />
<%= will_paginate @courses_list %>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hours</th>
      <th>Cohorts</th>
      <th colspan="3" class="edit-th">Edit</th>
      <th>New</th>
    </tr>
  </thead>

  <tbody>
    <% @courses_list.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.hours %></td>
        <td><% course.cohorts.each do |cohort| %>| 
          <%= link_to "#{cohort.name}", edit_cohort_path(cohort.id) %> |
          <% end %>
        </td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Create New Cohort Instance', new_cohort_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <%= will_paginate @courses_list %>

app/views/courses/new.html.erb
<br />
<h1>New Course</h1>
<br />
<hr>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<br />
<h1>
  <%= @course.name %>
</h1>
<br />
<hr>
<br />

<h3>Hours:</h3>
<%= @course.hours %><br />

<h3>Students taking subject:</h3>
<% @course.students.uniq.each do |student| %>
  <%= link_to "#{student.full_name}", student_path(student)%><br/>
<% end %>

<h3>Instructors teaching subject:</h3>
<% @course.instructors.uniq.each do |instructor| %>
  <%= link_to "#{instructor.full_name}", instructor_path(instructor)%><br/>
<% end %>
<br />

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>