config/routes.rb
Rails.application.routes.draw do
  resources :cohort_instructors
  resources :cohort_students
  resources :grades
  resources :cohorts
  resources :courses
  resources :students
  resources :instructors
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<% @quote = get_quotes %>
<% @rand = get_rand %>
<!DOCTYPE html>
<html>
  <head>
    <title>GTGo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Play" rel="stylesheet">
  </head>
    <header>
      <%= image_tag("gto-logo.png", id:"gto-logo") %>
      <h1>Admin Panel</h1>
      <span id="quote">"<i><%=@quote[@rand]%></i>" - Onizuka</span>
    </header>
  <div class="whole">
    <body>
    <hr>
    <section class="error-display">
      <span id="notice" style="color: white;"><%= notice %></span>
      <span id="error"><%= alert %></span>
    </section>
    <main class="container">
      <section id="box-1" class="main-info">
        <div class="admin-info">
          <% if signed_in? %>
          <%= image_tag("admin.png", id:"admin-icon") %>
          <br />
          <br />
            <strong>Signed in as:</strong> <%= current_user.email %>
            <br /><br />
            <%= button_to 'Sign out', sign_out_path, method: :delete %>
          <% else %>
            <%= image_tag("admin-not-logged.png", id:"admin-icon-not") %>
            <br />
            <%= link_to 'Sign in', sign_in_path %>
          <% end %>
        </div>
      <br />
      <nav>
        <% if signed_in?%>
          <strong>Courses:</strong> <%= link_to 'View', courses_path %> | <%= link_to 'New', new_course_path %><br />
          <strong>Cohorts:</strong> <%= link_to 'View', cohorts_path %> | <%= link_to 'New', new_cohort_path %><br />
          <strong>Instructors:</strong> <%= link_to 'View', instructors_path %> | <%= link_to 'New', new_instructor_path %><br />
          <strong>Students:</strong> <%= link_to 'View', students_path %> | <%= link_to 'New', new_student_path %><br />
        <% end %>
      </nav>
      </section>
      <section id="box-2" class="main-info">
        <%= yield %>
      </section>
    </main>
    </body>
  </div>
</html>